FROM openjdk:8-jdk-alpine
COPY target/altamar.jar altamar_backend.jar
CMD ["java","-jar","/BSS/target/altamar.jar"]
RUN mkdir -p /home/myapp/file_storage
ENTRYPOINT ["java","-jar","altamar_backend.jar"]
